// <auto-generated />
using IBACS.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IBACS.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526030232_CreateLocationHierarchies")]
    partial class CreateLocationHierarchies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IBACS.Server.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EquipmentKey"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EquipmentCategoryKey")
                        .HasColumnType("integer");

                    b.Property<int>("LocationKey")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("RTPageKey")
                        .HasColumnType("integer");

                    b.HasKey("EquipmentKey");

                    b.HasIndex("EquipmentCategoryKey");

                    b.HasIndex("LocationKey");

                    b.HasIndex("RTPageKey");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("IBACS.Server.Models.EquipmentCategory", b =>
                {
                    b.Property<int>("EquipmentCategoryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EquipmentCategoryKey"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("EquipmentCategoryKey");

                    b.ToTable("EquipmentCategories");
                });

            modelBuilder.Entity("IBACS.Server.Models.Location", b =>
                {
                    b.Property<int>("LocationKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationKey"));

                    b.Property<string>("FullName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("LocationTypeKey")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentLocationKey")
                        .HasColumnType("integer");

                    b.HasKey("LocationKey");

                    b.HasIndex("LocationTypeKey");

                    b.HasIndex("ParentLocationKey");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("IBACS.Server.Models.LocationType", b =>
                {
                    b.Property<int>("LocationTypeKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationTypeKey"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("LocationTypeKey");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LocationTypes");
                });

            modelBuilder.Entity("IBACS.Server.Models.Point", b =>
                {
                    b.Property<int>("PointKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PointKey"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EquipmentKey")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("PointKey");

                    b.HasIndex("EquipmentKey");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("IBACS.Server.Models.RTPage", b =>
                {
                    b.Property<int>("RTPageKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RTPageKey"));

                    b.Property<string>("PagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("RTPageKey");

                    b.ToTable("RTPages");
                });

            modelBuilder.Entity("IBACS.Server.Models.SystemModel", b =>
                {
                    b.Property<int>("SystemKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SystemKey"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("LocationKey")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("SystemKey");

                    b.HasIndex("LocationKey");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("IBACS.Server.Models.SystemPoint", b =>
                {
                    b.Property<int>("SysPointKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SysPointKey"));

                    b.Property<int>("PointKey")
                        .HasColumnType("integer");

                    b.Property<int>("SystemKey")
                        .HasColumnType("integer");

                    b.HasKey("SysPointKey");

                    b.HasIndex("PointKey");

                    b.HasIndex("SystemKey");

                    b.ToTable("SystemPoints");
                });

            modelBuilder.Entity("IBACS.Server.Models.Equipment", b =>
                {
                    b.HasOne("IBACS.Server.Models.EquipmentCategory", "EquipmentCategory")
                        .WithMany("Equipments")
                        .HasForeignKey("EquipmentCategoryKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IBACS.Server.Models.Location", "Location")
                        .WithMany("Equipments")
                        .HasForeignKey("LocationKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IBACS.Server.Models.RTPage", "RTPage")
                        .WithMany("Equipments")
                        .HasForeignKey("RTPageKey");

                    b.Navigation("EquipmentCategory");

                    b.Navigation("Location");

                    b.Navigation("RTPage");
                });

            modelBuilder.Entity("IBACS.Server.Models.Location", b =>
                {
                    b.HasOne("IBACS.Server.Models.LocationType", "LocationType")
                        .WithMany("Locations")
                        .HasForeignKey("LocationTypeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IBACS.Server.Models.Location", "ParentLocation")
                        .WithMany("ChildLocations")
                        .HasForeignKey("ParentLocationKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LocationType");

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("IBACS.Server.Models.Point", b =>
                {
                    b.HasOne("IBACS.Server.Models.Equipment", "Equipment")
                        .WithMany("Points")
                        .HasForeignKey("EquipmentKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("IBACS.Server.Models.SystemModel", b =>
                {
                    b.HasOne("IBACS.Server.Models.Location", "Location")
                        .WithMany("Systems")
                        .HasForeignKey("LocationKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("IBACS.Server.Models.SystemPoint", b =>
                {
                    b.HasOne("IBACS.Server.Models.Point", "Point")
                        .WithMany("SystemPoints")
                        .HasForeignKey("PointKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IBACS.Server.Models.SystemModel", "SystemModel")
                        .WithMany("SystemPoints")
                        .HasForeignKey("SystemKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");

                    b.Navigation("SystemModel");
                });

            modelBuilder.Entity("IBACS.Server.Models.Equipment", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("IBACS.Server.Models.EquipmentCategory", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("IBACS.Server.Models.Location", b =>
                {
                    b.Navigation("ChildLocations");

                    b.Navigation("Equipments");

                    b.Navigation("Systems");
                });

            modelBuilder.Entity("IBACS.Server.Models.LocationType", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("IBACS.Server.Models.Point", b =>
                {
                    b.Navigation("SystemPoints");
                });

            modelBuilder.Entity("IBACS.Server.Models.RTPage", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("IBACS.Server.Models.SystemModel", b =>
                {
                    b.Navigation("SystemPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
